# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 71))
        font = QtGui.QFont()
        font.setFamily("Swis721 BlkCn BT")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(130, 0, 0, 147), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(0, 330, 131, 120))
        self.btn_zero.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_zero.setAcceptDrops(False)
        self.btn_zero.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_zero.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_zero.setCheckable(False)
        self.btn_zero.setObjectName("btn_zero")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(130, 330, 151, 120))
        self.btn_equal.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_equal.setAcceptDrops(False)
        self.btn_equal.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_equal.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_equal.setCheckable(False)
        self.btn_equal.setObjectName("btn_equal")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 337, 121, 111))
        self.pushButton.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButton.setObjectName("btn_plus")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(280, 70, 121, 91))
        self.btn_plus.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 15pt \"MS Sans Serif\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.btn_plus.setIconSize(QtCore.QSize(40, 20))
        self.btn_plus.setObjectName("ptn_")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 160, 121, 91))
        self.pushButton_3.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 250, 121, 91))
        self.pushButton_4.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 70, 281, 271))
        self.widget.setStyleSheet("\n"
"background-color: rgb(243, 245, 255)")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(1, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_7 = QtWidgets.QPushButton(self.widget)
        self.btn_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_7.setAcceptDrops(False)
        self.btn_7.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_7.setIconSize(QtCore.QSize(90, 90))
        self.btn_7.setCheckable(False)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout_2.addWidget(self.btn_7, 2, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.widget)
        self.btn_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_5.setAcceptDrops(False)
        self.btn_5.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_5.setIconSize(QtCore.QSize(90, 90))
        self.btn_5.setCheckable(False)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout_2.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.widget)
        self.btn_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_4.setAcceptDrops(False)
        self.btn_4.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_4.setIconSize(QtCore.QSize(90, 90))
        self.btn_4.setCheckable(False)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout_2.addWidget(self.btn_4, 1, 0, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.widget)
        self.btn_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_1.setAcceptDrops(False)
        self.btn_1.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_1.setIconSize(QtCore.QSize(90, 90))
        self.btn_1.setCheckable(False)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout_2.addWidget(self.btn_1, 0, 0, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.widget)
        self.btn_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_3.setAcceptDrops(False)
        self.btn_3.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_3.setIconSize(QtCore.QSize(90, 90))
        self.btn_3.setCheckable(False)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout_2.addWidget(self.btn_3, 0, 2, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.widget)
        self.btn_9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_9.setAcceptDrops(False)
        self.btn_9.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_9.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_9.setIconSize(QtCore.QSize(90, 90))
        self.btn_9.setCheckable(False)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout_2.addWidget(self.btn_9, 2, 2, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.widget)
        self.btn_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_2.setAcceptDrops(False)
        self.btn_2.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_2.setIconSize(QtCore.QSize(90, 90))
        self.btn_2.setCheckable(False)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout_2.addWidget(self.btn_2, 0, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.widget)
        self.btn_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_6.setAcceptDrops(False)
        self.btn_6.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_6.setIconSize(QtCore.QSize(90, 90))
        self.btn_6.setCheckable(False)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout_2.addWidget(self.btn_6, 1, 2, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.widget)
        self.btn_8.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_8.setAcceptDrops(False)
        self.btn_8.setStyleSheet("background-color: rgb(236, 236, 177);\n"
"font: 75 26pt \"Futura Md BT\";")
        self.btn_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_8.setIconSize(QtCore.QSize(90, 90))
        self.btn_8.setCheckable(False)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout_2.addWidget(self.btn_8, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculate"))
        self.label.setText(_translate("MainWindow", "0"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.pushButton.setText(_translate("MainWindow", "+"))
        self.ptn_.setText(_translate("MainWindow", "/"))
        self.pushButton_3.setText(_translate("MainWindow", "*"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_8.setText(_translate("MainWindow", "8"))
    def add_functions(self):
        number=self.btn_zero.text()
        self.btn_zero.clicked.connect(lambda:self.write_number(number))
        self.btn_1.clicked.connect(lambda :self.btn_1(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.btn_2(self.btn_2.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_3.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_4.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_5.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_6.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_7.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_8.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_9.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_1.text()))
        self.btn_1.clicked.connect(lambda: self.btn_1(self.btn_1.text()))
    def write_number(self,number):
        print(number)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
